#!/bin/bash -e
# USAGE: ./scripts/get-kubernetes
# USAGE: ./scripts/get-kubernetes v1.4.0-alpha.8 

VERSION=${1:-"v1.2.4"}
DEST=${PWD}/bootcfg/assets/kubernetes/binaries/${VERSION}
BASE_URL=https://storage.googleapis.com/kubernetes-release/release/${VERSION}/bin/linux/amd64

if [ ! -d "${DEST}" ]; then
  echo "Creating directory ${DEST}"
  mkdir -p ${DEST}
fi

echo "Downloading Kubernetes Binaries" 

curl ${BASE_URL}/kubelet      -o ${DEST}/kubelet
curl ${BASE_URL}/kubelet.sha1 -o ${DEST}/kubelet.sha1

echo "$(cat ${DEST}/kubelet.sha1)  ${DEST}/kubelet" | sha1sum -c -

curl ${BASE_URL}/kube-apiserver      -o ${DEST}/kube-apiserver
curl ${BASE_URL}/kube-apiserver.sha1 -o ${DEST}/kube-apiserver.sha1

echo "$(cat ${DEST}/kube-apiserver.sha1) ${DEST}/kube-apiserver" | sha1sum -c -

curl ${BASE_URL}/kube-proxy      -o ${DEST}/kube-proxy
curl ${BASE_URL}/kube-proxy.sha1 -o ${DEST}/kube-proxy.sha1

echo "$(cat ${DEST}/kube-proxy.sha1) ${DEST}/kube-proxy" | sha1sum -c -

curl ${BASE_URL}/kube-scheduler      -o ${DEST}/kube-scheduler
curl ${BASE_URL}/kube-scheduler.sha1 -o ${DEST}/kube-scheduler.sha1

echo "$(cat ${DEST}/kube-scheduler.sha1) ${DEST}/kube-scheduler" | sha1sum -c -

curl ${BASE_URL}/kube-controller-manager      -o ${DEST}/kube-controller-manager
curl ${BASE_URL}/kube-controller-manager.sha1 -o ${DEST}/kube-controller-manager.sha1

echo "$(cat ${DEST}/kube-controller-manager.sha1) ${DEST}/kube-controller-manager" | sha1sum -c -

ln -s ${DEST} ${PWD}/bootcfg/assets/kubernetes/binaries/vendored
